### ISSUE TITLE
add backbuttons back to index

### ISSUE THREAD

**Issue by IceMints** [kendrajmoore/hackathon-portfolio#30]
To increase flow

**Comment by armandouv** [comment]
Would you mind elaborating a bit on this, please?

**Comment by IceMints** [comment]
There are links from index to profiles and projects but they do not link back to index. Just thought it would be nice for users to be able to go to those pages and get a link back to index without using the browser's back feature.

________________________________

**Comment by IceMints** [comment]
Added navigation routes in place of back buttons. Overall I think it is better.
